'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
const KEY='aqari-owner-properties';
export default function Admin(){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[filter,setFilter]=useState('pending');
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)||'[]'))}catch{setItems([])}},[]);
 const save=next=>{setItems(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const act=(index,status)=>save(items.map((x,i)=>i===index?{...x,status}:x));
 const visible=useMemo(()=>items.filter(x=>filter==='all'||x.status===filter),[items,filter]);
 return <main dir="rtl" className="content page admin"><header className="admin-head"><div><Link href="/">← عقاري</Link><h1>لوحة تحكم الإدارة</h1><p>مراجعة إعلانات أصحاب العقارات قبل ظهورها للزبائن.</p></div><div className="admin-stats"><b>{items.filter(x=>x.status==='pending'||x.status==='قيد المراجعة').length}<small>طلبات جديدة</small></b><b>{items.filter(x=>x.status==='published').length}<small>منشورة</small></b></div></header><div className="admin-tabs"><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>طلبات المراجعة</button><button className={filter==='published'?'active':''} onClick={()=>setFilter('published')}>المقبولة</button><button className={filter==='rejected'?'active':''} onClick={()=>setFilter('rejected')}>المرفوضة</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>الكل</button></div>{visible.length===0?<div className="empty">لا توجد طلبات في هذا القسم.</div>:<div className="admin-list">{visible.map((p)=>{const index=items.indexOf(p);return <article className="admin-card" key={index}><div className="admin-image">{p.images?.[0]?<span>📷</span>:<span>🏠</span>}</div><div className="admin-info"><span className="status">{p.status||'قيد المراجعة'}</span><h2>{p.title||'عقار بدون اسم'}</h2><p>{p.type} · {p.location} · {p.area} م²</p><p>الغرف: {p.rooms} · الحمامات: {p.baths} · الاستقبالات: {p.receptions}</p><strong>{p.price} د.ع</strong><small>المعلن: {p.owner?.name} · {p.owner?.phone}</small><div className="admin-actions"><button onClick={()=>setSelected(p)}>عرض التفاصيل</button>{p.status!=='published'&&<button className="approve" onClick={()=>act(index,'published')}>✓ موافقة ونشر</button>}{p.status!=='rejected'&&<button className="reject" onClick={()=>act(index,'rejected')}>✕ رفض</button>}</div></div></article>})}</div>}{selected&&<div className="overlay"><div className="detail admin-detail"><button className="x" onClick={()=>setSelected(null)}>×</button><h1>{selected.title}</h1><p><b>النوع:</b> {selected.type}</p><p><b>المحافظة:</b> {selected.owner?.city}</p><p><b>الموقع:</b> {selected.location}</p><p><b>السعر:</b> {selected.price} د.ع</p><p><b>المساحة:</b> {selected.area} م²</p><p><b>الغرف:</b> {selected.rooms} · <b>الحمامات:</b> {selected.baths} · <b>الاستقبالات:</b> {selected.receptions} · <b>المناور:</b> {selected.shafts||0}</p><p><b>الطوابق:</b> {selected.floors||0} · <b>المواقف:</b> {selected.parking||0}</p><p><b>ملاحظات:</b> {selected.notes||'لا توجد'}</p><p><b>المعلن:</b> {selected.owner?.name} — {selected.owner?.phone}</p><div className="contact"><button className="approve" onClick={()=>{act(items.indexOf(selected),'published');setSelected(null)}}>✓ موافقة ونشر</button><button className="reject" onClick={()=>{act(items.indexOf(selected),'rejected');setSelected(null)}}>✕ رفض الإعلان</button></div></div></div>}</main>
}
