'use client';
import { useMemo, useState } from 'react';

const properties=[
{id:1,type:'منزل',title:'بيت عائلي حديث في الحي الراقي',location:'كركوك - الحي الراقي',price:385000000,area:'250 م²',beds:4,baths:3,parking:2,image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',phone:'+9647500000000'},
{id:2,type:'أرض',title:'قطعة أرض سكنية مميزة',location:'كركوك - طريق بغداد',price:95000000,area:'300 م²',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85',phone:'+9647500000000'},
{id:3,type:'شقة',title:'شقة واسعة جاهزة للسكن',location:'كركوك - دوميز',price:125000000,area:'150 م²',beds:3,baths:2,parking:1,image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85',phone:'+9647500000000'},
{id:4,type:'محل',title:'محل تجاري على شارع رئيسي',location:'كركوك - طريق بغداد',price:210000000,area:'80 م²',baths:1,image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85',phone:'+9647500000000'},
{id:5,type:'منزل',title:'دار طابقين مع حديقة',location:'كركوك - حي النصر',price:265000000,area:'240 م²',beds:5,baths:3,parking:2,image:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85',phone:'+9647500000000'},
{id:6,type:'مشتمل',title:'مشتمل مستقل بموقع هادئ',location:'كركوك - الشورجة',price:70000000,area:'100 م²',beds:2,baths:1,parking:1,image:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85'}
];
const cats=[['الكل','الكل'],['منازل','منزل'],['شقق','شقة'],['قطع أرض','أرض'],['مشتملات','مشتمل'],['محلات','محل'],['مخازن','مخزن']];
const money=n=>new Intl.NumberFormat('ar-IQ').format(n)+' د.ع';
export default function Complete(){
 const [page,setPage]=useState('home'),[cat,setCat]=useState('الكل'),[q,setQ]=useState(''),[fav,setFav]=useState([]),[selected,setSelected]=useState(null),[notice,setNotice]=useState('');
 const list=useMemo(()=>properties.filter(p=>(cat==='الكل'||p.type===cat)&&(!q||(`${p.title} ${p.location}`).includes(q))),[cat,q]);
 const go=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'});};
 const notify=t=>{setNotice(t);setTimeout(()=>setNotice(''),2200)};
 return <main dir="rtl" className="complete-app">
 <header className="header"><button onClick={()=>go('home')} className="logo">⌂ <b>عقاري</b><small>سوق كركوك</small></button><div><button onClick={()=>go('favorites')}>♡ المفضلة</button><button onClick={()=>go('add')} className="gold">＋ أضف إعلان</button></div></header>
 {page==='home'&&<><section className="hero"><h1>ابحث عن عقارك المثالي</h1><p>بيوت، شقق، أراضي ومحلات في كركوك</p><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن منطقة أو عقار..."/><button onClick={()=>go('properties')}>بحث</button></div></section><section className="content"><div className="cats">{cats.map(c=><button className={cat===c[0]?'active':''} onClick={()=>setCat(c[0])} key={c[0]}>{c[0]}</button>)}</div><h2>استكشف العقارات <small>{list.length} عقار</small></h2><Cards list={list} fav={fav} setFav={setFav} open={setSelected}/></section></>}
 {page==='properties'&&<section className="content page"><h1>كل العقارات</h1><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث..."/><button>بحث</button></div><div className="cats">{cats.map(c=><button className={cat===c[0]?'active':''} onClick={()=>setCat(c[0])} key={c[0]}>{c[0]}</button>)}</div><Cards list={list} fav={fav} setFav={setFav} open={setSelected}/></section>}
 {page==='favorites'&&<section className="content page"><h1>المفضلة</h1>{fav.length?<Cards list={properties.filter(p=>fav.includes(p.id))} fav={fav} setFav={setFav} open={setSelected}/>:<div className="empty">لم تضف أي عقار للمفضلة بعد ❤️</div>}</section>}
 {page==='messages'&&<section className="content page"><h1>الرسائل</h1><div className="empty">لا توجد رسائل حالياً.<br/><button className="gold" onClick={()=>notify('عند مراسلة صاحب أي عقار ستظهر المحادثة هنا')}>كيف أرسل رسالة؟</button></div></section>}
 {page==='add'&&<Add notify={notify}/>} 
 {page==='more'&&<section className="content page"><h1>المزيد</h1><div className="menu">{['من نحن','شروط الاستخدام','سياسة الخصوصية','مساعدة ودعم','الإبلاغ عن إعلان'].map(x=><button key={x} onClick={()=>notify('سيتم فتح قسم '+x)}>{x}<span>←</span></button>)}</div></section>}
 <nav><button onClick={()=>go('more')}>☰<small>المزيد</small></button><button onClick={()=>go('favorites')}>♡<small>المفضلة</small></button><button className="plus" onClick={()=>go('add')}>＋</button><button onClick={()=>go('messages')}>▱<small>الرسائل</small></button><button onClick={()=>go('home')}>⌂<small>الرئيسية</small></button></nav>
 {selected&&<Detail p={selected} close={()=>setSelected(null)} notify={notify}/>} {notice&&<div className="toast">{notice}</div>}
 </main>
}
function Cards({list,fav,setFav,open}){return <div className="grid">{list.map(p=><article className="card" key={p.id}><div className="photo"><img src={p.image}/><span>للبيع</span><button onClick={()=>setFav(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id])}>{fav.includes(p.id)?'♥':'♡'}</button></div><div className="body"><small>⌖ {p.location}</small><h3>{p.title}</h3><strong>{money(p.price)}</strong><p>{p.area} {p.beds?` · ${p.beds} غرف`:''} {p.baths?` · ${p.baths} حمام`:''}</p><button className="details" onClick={()=>open(p)}>عرض التفاصيل ←</button></div></article>)}</div>}
function Detail({p,close,notify}){return <div className="overlay"><div className="detail"><button className="x" onClick={close}>×</button><img src={p.image}/><div><span>{p.type} · للبيع</span><h1>{p.title}</h1><p>⌖ {p.location}</p><h2>{money(p.price)}</h2><div className="facts"><b>المساحة<br/>{p.area}</b>{p.beds&&<b>الغرف<br/>{p.beds}</b>}{p.baths&&<b>الحمامات<br/>{p.baths}</b>}{p.parking&&<b>المواقف<br/>{p.parking}</b>}</div><p>عقار مميز في موقع جيد. تواصل مباشرة مع المعلن لمعرفة التفاصيل والموقع وموعد المعاينة.</p><div className="contact"><a href={'tel:'+p.phone}>📞 اتصال</a><a href={'https://wa.me/'+p.phone.replace('+','')} target="_blank">💬 واتساب</a><button onClick={()=>notify('تم حفظ طلب التواصل')} >✉ مراسلة</button></div></div></div></div>}
function Add({notify}){const [sent,setSent]=useState(false);return <section className="content page"><h1>أضف إعلانك</h1><p>التصفح مجاني. املأ البيانات وسيتم تجهيز إعلانك للمراجعة.</p><div className="form">{['اسم العقار','السعر بالدينار','الموقع / المنطقة','المساحة','رقم الهاتف'].map(x=><input key={x} placeholder={x}/>)}<select><option>اختر النوع</option><option>منزل</option><option>شقة</option><option>قطعة أرض</option><option>مشتمل</option><option>محل</option><option>مخزن</option></select><textarea placeholder="وصف العقار والتفاصيل..."></textarea><button className="gold" onClick={()=>{setSent(true);notify('تم إرسال الإعلان للمراجعة')}}>{sent?'تم الإرسال ✓':'نشر الإعلان'}</button></div></section>}
