'use client';
import Complete from './page';
export default function Redesign(){return <><Complete/><style>{`/* Aqari visual redesign: reference-style mobile property marketplace */
.app{background:#f4f6fa!important;color:#172033!important;padding-bottom:82px!important}
.header{height:64px!important;padding:0 12px!important;background:#ffffffee!important;border-bottom:1px solid #e8edf2!important}
.header .logo{font-size:0!important;line-height:1!important}.header .logo b{font-size:24px!important;color:#172033!important}.header .logo small{font-size:9px!important;color:#8c96a3!important}
.header .head-actions button:not(.gold){display:none!important}.header .head-actions{gap:6px!important}.header .head-actions .gold{background:#1769c2!important;border-radius:15px!important;padding:9px 12px!important}
.hero{background:#f4f6fa!important;color:#172033!important;padding:14px 12px 8px!important;text-align:initial!important;display:block!important}
.hero .eyebrow,.hero h1,.hero p,.province-box{display:none!important}
.hero .search{max-width:none!important;margin:0!important;height:58px!important;background:#fff!important;border:1px solid #e0e5eb!important;border-radius:30px!important;padding:5px!important;box-shadow:0 4px 15px #17203309!important}
.hero .search input{font-size:14px!important;color:#172033!important;padding:0 14px!important}.hero .search button{width:48px!important;height:48px!important;border-radius:24px!important;background:#1769c2!important;color:#fff!important}
.content{max-width:760px!important;margin:auto!important;padding:6px 12px 100px!important}.content>.ai{display:none!important}.content>.quick{display:none!important}.content>.section-title:first-of-type{margin-top:5px!important}
.cats{gap:7px!important;padding:6px 0 13px!important}.cats button{background:#fff!important;border:1px solid #e1e6ec!important;border-radius:22px!important;padding:10px 14px!important}.cats .active{background:#1769c2!important;border-color:#1769c2!important;color:#fff!important}
.grid{display:grid!important;grid-template-columns:1fr!important;gap:10px!important}
.card{display:flex!important;flex-direction:row!important;min-height:184px!important;height:184px!important;border-radius:21px!important;margin:0!important;overflow:hidden!important;box-shadow:0 4px 16px #1720330a!important;border:1px solid #e8edf2!important}
.card .photo{width:53%!important;height:184px!important;min-height:184px!important;position:relative!important;order:0!important}.card .photo img{width:100%!important;height:100%!important;object-fit:cover!important}.card .photo span{display:none!important}.card .photo button{top:10px!important;left:10px!important;width:42px!important;height:42px!important;border-radius:50%!important;background:#fff!important;color:#d54c62!important;font-size:23px!important}
.card .body{direction:rtl!important;width:47%!important;padding:11px!important;display:flex!important;flex-direction:column!important;justify-content:space-between!important}.card .body small{font-size:11px!important;color:#4e5866!important;text-align:right!important}.card .body h3{font-size:14px!important;margin:4px 0!important;text-align:right!important;line-height:1.35!important}.card .body strong{font-size:16px!important;color:#1769c2!important;text-align:right!important}.card .meta{display:flex!important;gap:7px!important;margin:3px 0!important;font-size:9px!important}.card .actions{display:block!important;border:0!important;padding:0!important}.card .actions button{display:none!important}.card .actions button:last-child{display:flex!important;width:100%!important;height:34px!important;border-radius:18px!important;background:#f0f6fd!important;color:#1769c2!important;align-items:center!important;justify-content:center!important;font-size:11px!important;font-weight:800!important}
.stories,.story{display:none!important}.section-title{margin:8px 0 11px!important}.section-title h2{font-size:19px!important}.section-title button{color:#1769c2!important;font-size:12px!important}
.nav{height:76px!important;background:#ffffffed!important;border-top:1px solid #e3e8ee!important}.nav button{font-size:19px!important;color:#8a94a1!important}.nav small{font-size:9px!important}.nav .gold{width:58px!important;height:58px!important;border-radius:50%!important;background:#1769c2!important;color:#fff!important;margin-top:-28px!important;box-shadow:0 3px 0 #fff!important}
/* search/results screens */
.page{min-height:80vh!important}.page .grid{grid-template-columns:1fr!important}.page .card{height:184px!important}.page .card .photo{height:184px!important}
.overlay{background:#061321aa!important}.detail{border-radius:24px!important}.detail>img{height:270px!important}.contact button{background:#1769c2!important}.auth .gold{background:#1769c2!important}
@media(max-width:650px){.header .head-actions .gold{font-size:10px!important}.content{padding-left:10px!important;padding-right:10px!important}.hero{padding:10px 10px 6px!important}.card,.card .photo{height:181px!important;min-height:181px!important}.card .body{padding:9px!important}.card .body h3{font-size:13px!important}.card .body strong{font-size:14px!important}.card .body small{font-size:10px!important}.card .meta{font-size:8px!important}.card .actions button:last-child{height:32px!important;font-size:10px!important}}
`}</style></>}
