'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

const properties=[
 {id:'1',title:'دار سكنية حديثة في حي الواسطي',type:'دار',city:'كركوك',area:'الواسطي',price:185000000,rooms:4,size:240,img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',featured:true},
 {id:'2',title:'شقة راقية قرب شارع بغداد',type:'شقة',city:'كركوك',area:'شارع بغداد',price:125000000,rooms:3,size:165,img:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=80'},
 {id:'3',title:'قطعة أرض تجارية على شارع رئيسي',type:'أرض',city:'الموصل',area:'الدواسة',price:320000000,rooms:0,size:500,img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=80',featured:true},
 {id:'4',title:'مشتمل مستقل مع حديقة',type:'مشتمل',city:'كركوك',area:'حي العسكري',price:98000000,rooms:2,size:120,img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80'},
 {id:'5',title:'محل تجاري جاهز للاستثمار',type:'محل',city:'بغداد',area:'المنصور',price:275000000,rooms:0,size:90,img:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=80'},
 {id:'6',title:'مخزن واسع مع مدخل شاحنات',type:'مخزن',city:'نينوى',area:'الجانب الأيمن',price:410000000,rooms:0,size:800,img:'https://images.unsplash.com/photo-1586528116493-da8b6f2a5a17?auto=format&fit=crop&w=1000&q=80'}
];
const types=['الكل','دار','شقة','أرض','مشتمل','محل','مخزن'];
const provinces=['كل المحافظات','كركوك','الموصل','بغداد','نينوى'];
function money(n:number){return new Intl.NumberFormat('ar-IQ').format(n)+' د.ع'}
function Nav(){return <><header className="topbar"><Link href="/" className="brand">عقاري <span>IQ</span></Link><div className="toplinks"><Link href="/publish"><button className="goldbtn">+ نشر عقار</button></Link><Link href="/account"><button className="navbtn">حسابي</button></Link></div></header><nav className="bottom"><Link href="/">⌂ الرئيسية</Link><Link href="/properties">⌕ العقارات</Link><Link href="/services">🛠 الحرفيون</Link><Link href="/store">▣ المتجر</Link><Link href="/cart">🛒 السلة</Link><Link href="/account">👤 حسابي</Link></nav></>}
function Card({p,fav,setFav}:{p:any;fav:string[];setFav:(x:string[])=>void}){const on=fav.includes(p.id);return <article className="card"><div className="photo"><img src={p.img} alt=""/><span className="badge">{p.featured?'مميز':'موثّق'}</span><button className="heart" onClick={()=>setFav(on?fav.filter(x=>x!==p.id):[...fav,p.id])}>{on?'♥':'♡'}</button></div><div className="body"><div className="price">{money(p.price)}</div><h3>{p.title}</h3><div className="muted">{p.city} · {p.area}</div><div className="muted" style={{marginTop:8}}>{p.size} م² {p.rooms?`· ${p.rooms} غرف`:''}</div><div className="actions"><Link href={'/property/'+p.id}><button className="goldbtn detailsBtn">عرض التفاصيل</button></Link><Link href="/booking"><button className="outlinebtn">احجز معاينة</button></Link></div></div></article>}
function Properties({fav,setFav}:{fav:string[];setFav:(x:string[])=>void}){const [q,setQ]=useState('');const [type,setType]=useState('الكل');const [prov,setProv]=useState('كل المحافظات');const filtered=useMemo(()=>properties.filter(p=>(type==='الكل'||p.type===type)&&(prov==='كل المحافظات'||p.city===prov||p.city==='نينوى'&&prov==='الموصل')&&(`${p.title} ${p.area} ${p.city}`).includes(q)),[q,type,prov]);return <main className="container section"><div className="sectionhead"><div><div className="eyebrow">سوق العقارات العراقي</div><h1>اكتشف عقارك القادم</h1></div><Link href="/compare"><button className="outlinebtn">مقارنة العقارات</button></Link></div><div className="form"><div className="search" style={{margin:0,maxWidth:'none'}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن موقع أو اسم منطقة..."/><button className="goldbtn">بحث</button></div><div className="chips" style={{marginTop:12}}>{types.map(t=><button key={t} className={'chip '+(type===t?'active':'')} onClick={()=>setType(t)}>{t}</button>)}</div><select value={prov} onChange={e=>setProv(e.target.value)} style={{marginTop:12,padding:10,borderRadius:12}}>{provinces.map(x=><option key={x}>{x}</option>)}</select></div><div className="grid" style={{marginTop:18}}>{filtered.map(p=><Card key={p.id} p={p} fav={fav} setFav={setFav}/>)}{!filtered.length&&<div className="feature">لا توجد نتائج مطابقة. جرّب تغيير الفلاتر.</div>}</div></main>}
const sevenFeatures=[
 ['✦','المساعد العقاري الذكي','/ai'],
 ['⚖','مقارنة العقارات','/compare'],
 ['📅','حجز موعد المعاينة','/booking'],
 ['▣','الحاسبة العقارية و ROI','/calculator'],
 ['📍','الموقع والاتجاهات','/properties'],
 ['♥','العقارات المفضلة','/favorites'],
 ['🛠','الحرفيون وخدمات البناء','/services']
];
function Home({fav,setFav,dark,setDark}:{fav:string[];setFav:(x:string[])=>void;dark:boolean;setDark:(x:boolean)=>void}){return <main className="container"><section className="hero"><div className="eyebrow">منصة عقارية عراقية ذكية</div><h1>بيتك يبدأ من هنا.</h1><p>ابحث، قارن، احجز المعاينة، وتواصل مباشرة مع المالك. تجربة مصممة للسوق العراقي من كركوك إلى كل المحافظات.</p><div className="search"><input placeholder="ابحث عن موقع أو اسم منطقة..."/><Link href="/properties"><button className="goldbtn">استكشف العقارات</button></Link></div></section><section className="section"><div className="sectionhead"><h2>الوصول السريع</h2><button className="outlinebtn" onClick={()=>setDark(!dark)}>{dark?'☀ الوضع النهاري':'◐ الوضع الليلي'}</button></div><div className="sevenFeatures">{sevenFeatures.map(([icon,title,href])=><Link href={href} className="sevenFeature" key={title}><span className="sevenIcon">{icon}</span><span>{title}</span><b>←</b></Link>)}</div></section><section className="section"><div className="sectionhead"><h2>عقارات مميزة</h2><Link href="/properties">عرض الكل ←</Link></div><div className="grid">{properties.slice(0,3).map(p=><Card key={p.id} p={p} fav={fav} setFav={setFav}/>)}</div></section></main>}
function Detail({id}:{id:string}){const p=properties.find(x=>x.id===id)||properties[0];return <main className="container section"><Link href="/properties">← العودة للعقارات</Link><div className="card" style={{marginTop:16}}><div className="photo" style={{height:360}}><img src={p.img} alt=""/></div><div className="body"><div className="eyebrow">{p.city} · {p.area}</div><h1>{p.title}</h1><div className="price">{money(p.price)}</div><p className="muted">المساحة {p.size} م² {p.rooms?` · ${p.rooms} غرف`:''} · الموقع متاح على الخريطة</p><div className="features"><div className="feature"><strong>📍 الموقع والاتجاه</strong><span className="muted">عرض الموقع التقريبي وفتح الاتجاهات.</span></div><div className="feature"><strong>📈 ROI</strong><span className="muted">تقدير العائد الاستثماري من الحاسبة.</span></div></div><div className="actions"><Link href="/booking"><button className="goldbtn">احجز موعد معاينة</button></Link><button className="outlinebtn" onClick={()=>window.open('https://wa.me/9647500000000','_blank')}>واتساب المالك</button></div></div></div></main>}
function Page({slug,fav,setFav,dark,setDark}:{slug:string[];fav:string[];setFav:(x:string[])=>void;dark:boolean;setDark:(x:boolean)=>void}){const path=slug.join('/');if(path==='')return <Home fav={fav} setFav={setFav} dark={dark} setDark={setDark}/>;if(path==='properties')return <Properties fav={fav} setFav={setFav}/>;if(path.startsWith('property/'))return <Detail id={path.split('/')[1]}/>;if(path==='favorites')return <main className="container section"><h1>المفضلة</h1><div className="grid">{properties.filter(p=>fav.includes(p.id)).map(p=><Card key={p.id} p={p} fav={fav} setFav={setFav}/>)}</div>{!fav.length&&<div className="feature">لم تضف عقارات للمفضلة بعد.</div>}</main>;if(path==='booking')return <main className="container section"><h1>حجز موعد المعاينة</h1><div className="form"><p className="muted">اختر اليوم والوقت المناسبين، وسيتم حفظ طلبك على هذا الجهاز.</p><div className="field"><label>العقار</label><select><option>دار سكنية حديثة في حي الواسطي</option><option>شقة راقية قرب شارع بغداد</option></select></div><div className="field"><label>التاريخ</label><input type="date"/></div><div className="field"><label>الوقت</label><select><option>04:00 مساءً</option><option>05:00 مساءً</option><option>06:00 مساءً</option></select></div><button className="goldbtn" onClick={()=>alert('تم تسجيل طلب المعاينة بنجاح')}>تأكيد الحجز</button></div></main>;if(path==='publish')return <main className="container section"><h1>نشر عقار</h1><div className="form"><div className="field"><label>عنوان العقار</label><input placeholder="مثال: دار حديثة في حي..."/></div><div className="field"><label>المحافظة</label><select>{provinces.slice(1).map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>النوع</label><select>{types.slice(1).map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>السعر التقريبي</label><input type="number" placeholder="د.ع"/></div><div className="field"><label>الوصف</label><textarea rows={5} placeholder="أضف التفاصيل والمميزات..."/></div><button className="goldbtn" onClick={()=>alert('تم إرسال العقار للمراجعة، ولن يظهر للعامة قبل موافقة الإدارة.')}>إرسال للمراجعة</button></div></main>;if(path==='compare')return <main className="container section"><h1>مقارنة العقارات</h1><div className="grid">{properties.slice(0,3).map(p=><div className="feature" key={p.id}><strong>{p.title}</strong><p>{money(p.price)}</p><p className="muted">{p.size} م² · {p.city}</p><p>السعر/م²: {money(Math.round(p.price/p.size))}</p></div>)}</div></main>;if(path==='calculator')return <Calculator/>;if(path==='ai')return <AI/>;if(path==='services')return <Services/>;if(path==='store')return <Store/>;if(path==='cart')return <Cart/>;if(path==='account')return <Account/>;return <main className="container section"><h1>الصفحة غير موجودة</h1><Link href="/">العودة للرئيسية</Link></main>}
function Calculator(){const [price,setPrice]=useState(150000000);const [rent,setRent]=useState(900000);const [years,setYears]=useState(10);const roi=price?((rent*12/price)*100).toFixed(2):'0';return <main className="container section"><h1>الحاسبة العقارية الذكية</h1><div className="form"><div className="field"><label>قيمة العقار</label><input type="number" value={price} onChange={e=>setPrice(+e.target.value)}/></div><div className="field"><label>الإيجار الشهري المتوقع</label><input type="number" value={rent} onChange={e=>setRent(+e.target.value)}/></div><div className="field"><label>مدة الاستثمار بالسنوات</label><input type="number" value={years} onChange={e=>setYears(+e.target.value)}/></div><div className="stats"><div className="stat"><span className="muted">ROI سنوي</span><br/><b>{roi}%</b></div><div className="stat"><span className="muted">دخل سنوي</span><br/><b>{money(rent*12)}</b></div><div className="stat"><span className="muted">إجمالي الإيجار</span><br/><b>{money(rent*12*years)}</b></div><div className="stat"><span className="muted">السعر/م²</span><br/><b>—</b></div></div></div></main>}
function AI(){const [q,setQ]=useState('');const [answer,setAnswer]=useState('');return <main className="container section"><div className="hero"><div className="eyebrow">AI REAL ESTATE CONCIERGE</div><h1>احچيلي شتريد.</h1><p>مثال: أريد دار بكركوك، 4 غرف، قريبة من الخدمات وبحدود 200 مليون.</p><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اكتب طلبك باللهجة العراقية..."/><button className="goldbtn" onClick={()=>setAnswer('فهمت طلبك: '+q+' — أنصحك بالبدء من العقارات المميزة ثم مقارنة السعر والمساحة والموقع.')}>حلّل الطلب</button></div></div>{answer&&<div className="feature"><strong>نتيجة المساعد</strong><p>{answer}</p><Link href="/properties"><button className="goldbtn">عرض العقارات المناسبة</button></Link></div>}</main>}
function Services(){const s=['كهربائي','سباك','صباغ','حداد','تبريد وتكييف','بناء','تبليط','حدائق'];return <main className="container section"><h1>الحرفيون وخدمات البناء</h1><p className="muted">اختر الخدمة ثم تواصل مع مقدم الخدمة.</p><div className="grid">{s.map(x=><div className="feature" key={x}><div style={{fontSize:30}}>🛠</div><strong>{x}</strong><span className="muted">خدمة محلية · تقييمات · تواصل مباشر</span><div className="actions"><button className="goldbtn" onClick={()=>alert('تم اختيار '+x)}>طلب الخدمة</button></div></div>)}</div></main>}
function Store(){return <main className="container section"><h1>متجر مواد البناء</h1><div className="grid">{['سمنت','حديد تسليح','دهانات','بلاط','أدوات كهربائية','أدوات صحية'].map((x,i)=><div className="feature" key={x}><div style={{fontSize:34}}>▦</div><strong>{x}</strong><p className="muted">السعر حسب الكمية والموقع</p><button className="goldbtn" onClick={()=>{const c=JSON.parse(localStorage.getItem('cart')||'[]');c.push(x);localStorage.setItem('cart',JSON.stringify(c));alert('أضيف للسلة')}}>أضف للسلة</button></div>)}</div></main>}
function Cart(){const [items,setItems]=useState<string[]>([]);useEffect(()=>setItems(JSON.parse(localStorage.getItem('cart')||'[]')),[]);return <main className="container section"><h1>السلة</h1><div className="feature">{items.length?items.map((x,i)=><p key={i}>• {x}</p>):'السلة فارغة.'}<br/><button className="goldbtn" onClick={()=>{localStorage.removeItem('cart');setItems([])}}>إفراغ السلة</button></div></main>}
function Account(){const [name,setName]=useState('');return <main className="container section"><h1>حسابي</h1><div className="form"><div className="field"><label>الاسم</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="الاسم الكامل"/></div><div className="field"><label>رقم الهاتف</label><input placeholder="07xxxxxxxxx"/></div><div className="actions"><Link href="/favorites"><button className="outlinebtn">♥ المفضلة</button></Link><Link href="/publish"><button className="goldbtn">نشر عقار</button></Link></div><p className="muted">التصفح متاح بدون حساب. الحساب مطلوب للتواصل وبعض الإجراءات.</p></div></main>}
export default function App({slug}:{slug?:string[]}){const [fav,setFav]=useState<string[]>([]);const [dark,setDark]=useState(false);useEffect(()=>setFav(JSON.parse(localStorage.getItem('fav')||'[]')),[]);useEffect(()=>localStorage.setItem('fav',JSON.stringify(fav)),[fav]);return <div className={'app '+(dark?'dark':'')}><Nav/><Page slug={slug||[]} fav={fav} setFav={setFav} dark={dark} setDark={setDark}/></div>}
