'use client';
import { useMemo, useState } from 'react';

type Property={type:string;title:string;area:string;price:string;size:string;rooms?:string;image:string};
const properties:Property[]=[
{type:'منزل',title:'بيت عائلي حديث في حي الواسطي',area:'الواسطي',price:'185,000,000',size:'200 م²',rooms:'4 غرف',image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80'},
{type:'أرض',title:'قطعة أرض سكنية مميزة',area:'طريق بغداد',price:'95,000,000',size:'300 م²',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80'},
{type:'شقة',title:'شقة واسعة جاهزة للسكن',area:'دوميز',price:'125,000,000',size:'150 م²',rooms:'3 غرف',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80'},
{type:'محل',title:'محل تجاري على شارع رئيسي',area:'طريق بغداد',price:'210,000,000',size:'80 م²',image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80'}];
const categories=['الكل','منازل','شقق','قطع أرض','محلات'];
export default function Home(){const [category,setCategory]=useState('الكل');const [query,setQuery]=useState('');const filtered=useMemo(()=>properties.filter(p=>(category==='الكل'||(category==='منازل'&&p.type==='منزل')||(category==='شقق'&&p.type==='شقة')||(category==='قطع أرض'&&p.type==='أرض')||(category==='محلات'&&p.type==='محل'))&&(!query||p.title.includes(query)||p.area.includes(query))),[category,query]);return <main><header className="wrap top"><strong>⌂ عقاري</strong><span>سوق كركوك العقاري</span></header><section className="hero wrap"><small>● عقارات كركوك</small><h1>بيتك الجديد<br/><span>يبدأ من هنا.</span></h1><p>اكتشف المنازل والشقق والأراضي والمحلات المعروضة للبيع في كركوك، وتواصل مباشرة مع صاحب العقار.</p><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن منطقة أو نوع عقار..."/><button>بحث</button></div></section><section className="wrap"><h2>العقارات المتاحة</h2><div className="cats">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="grid">{filtered.map(p=><article className="card" key={p.title}><img src={p.image} alt={p.title}/><div className="body"><small>كركوك · {p.area}</small><h3>{p.title}</h3><p>{p.size}{p.rooms&&` · ${p.rooms}`}</p><b>{p.price} د.ع</b><button className="details" onClick={()=>alert(`للتواصل مع صاحب العقار: 07500000000`)}>التفاصيل والتواصل</button></div></article>)}</div></section><footer className="wrap">⌂ عقاري <span>© 2026 · منصة العقارات في كركوك</span></footer></main>}