'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import ProFeaturesButton from './pro-features-modal';

const properties=[
 {id:'1',title:'دار سكنية حديثة في حي الواسطي',type:'دار',city:'كركوك',area:'الواسطي',price:185000000,rooms:4,size:240,img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',featured:true},
 {id:'2',title:'شقة راقية قرب شارع بغداد',type:'شقة',city:'كركوك',area:'شارع بغداد',price:125000000,rooms:3,size:165,img:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=80'},
 {id:'3',title:'قطعة أرض تجارية على شارع رئيسي',type:'أرض',city:'الموصل',area:'الدواسة',price:320000000,rooms:0,size:500,img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=80',featured:true},
 {id:'4',title:'مشتمل مستقل مع حديقة',type:'مشتمل',city:'كركوك',area:'حي العسكري',price:98000000,rooms:2,size:120,img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80'},
 {id:'5',title:'محل تجاري جاهز للاستثمار',type:'محل',city:'بغداد',area:'المنصور',price:275000000,rooms:0,size:90,img:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=80'},
 {id:'6',title:'مخزن واسع مع مدخل شاحنات',type:'مخزن',city:'نينوى',area:'الجانب الأيمن',price:410000000,rooms:0,size:800,img:'https://images.unsplash.com/photo-1586528116493-da8b6f2a5a17?auto=format&fit=crop&w=1000&q=80'},
 {id:'7',title:'دار عائلية واسعة مع كراج',type:'دار',city:'كركوك',area:'حي النصر',price:235000000,rooms:5,size:300,img:'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1000&q=80',featured:true},
 {id:'8',title:'شقة مفروشة جاهزة للسكن',type:'شقة',city:'بغداد',area:'الجادرية',price:195000000,rooms:3,size:180,img:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=80'},
 {id:'9',title:'قطعة أرض سكنية بموقع هادئ',type:'أرض',city:'كركوك',area:'حي الواسطي الجديد',price:85000000,rooms:0,size:250,img:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=80'},
 {id:'10',title:'أرض تجارية على شارع حيوي',type:'أرض',city:'بغداد',area:'الكرادة',price:480000000,rooms:0,size:650,img:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=80',featured:true},
 {id:'11',title:'شقة عصرية بإطلالة جميلة',type:'شقة',city:'الموصل',area:'حي الجامعة',price:145000000,rooms:3,size:170,img:'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80'},
 {id:'12',title:'بيت طابقين مع حديقة أمامية',type:'دار',city:'نينوى',area:'الموصل الجديدة',price:290000000,rooms:6,size:360,img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=80',featured:true},
 {id:'13',title:'مشتمل مستقل قريب من الخدمات',type:'مشتمل',city:'كركوك',area:'حي الواسطي',price:110000000,rooms:2,size:135,img:'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80'},
 {id:'14',title:'محل تجاري بواجهة زجاجية',type:'محل',city:'الموصل',area:'شارع النجفي',price:210000000,rooms:0,size:110,img:'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&w=1000&q=80'},
 {id:'15',title:'مخزن صناعي كبير مع ساحة',type:'مخزن',city:'بغداد',area:'النهروان',price:560000000,rooms:0,size:1200,img:'https://images.unsplash.com/photo-1565610222536-ef125c59da2e?auto=format&fit=crop&w=1000&q=80'},
 {id:'16',title:'شقة استثمارية مناسبة للإيجار',type:'شقة',city:'كركوك',area:'شارع أطلس',price:135000000,rooms:2,size:140,img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80'},
 {id:'17',title:'دار حديثة بتصميم فاخر',type:'دار',city:'بغداد',area:'المنصور',price:425000000,rooms:5,size:420,img:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=80',featured:true},
 {id:'18',title:'قطعة أرض مناسبة لبناء منزل',type:'أرض',city:'نينوى',area:'بعشيقة',price:72000000,rooms:0,size:300,img:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80'}
];
const types=['الكل','دار','شقة','أرض','مشتمل','محل','مخزن'];
const provinces=['كل المحافظات','كركوك','الموصل','بغداد','نينوى'];
function money(n:number){return new Intl.NumberFormat('ar-IQ').format(n)+' د.ع'}
function Nav(){return <><header className="topbar"><Link href="/" className="brand">عقاري <span>IQ</span></Link><div className="toplinks"><Link href="/publish"><button className="goldbtn">+ نشر عقار</button></Link><Link href="/account"><button className="navbtn">حسابي</button></Link></div></header><nav className="bottom"><Link href="/">⌂ الرئيسية</Link><Link href="/properties">⌕ العقارات</Link><Link href="/services">🛠 الحرفيون</Link><Link href="/store">▣ المتجر</Link><Link href="/cart">🛒 السلة</Link><Link href="/account">👤 حسابي</Link></nav></>}
function Card({p,fav,setFav}:{p:any;fav:string[];setFav:(x:string[])=>void}){const on=fav.includes(p.id);return <article className="card"><div className="photo"><img src={p.img} alt=""/><span className="badge">{p.featured?'مميز':'موثّق'}</span><button className="heart" onClick={()=>setFav(on?fav.filter(x=>x!==p.id):[...fav,p.id])}>{on?'♥':'♡'}</button></div><div className="body"><div className="price">{money(p.price)}</div><h3>{p.title}</h3><div className="muted">{p.city} · {p.area}</div><div className="muted" style={{marginTop:8}}>{p.size} م² {p.rooms?`· ${p.rooms} غرف`:''}</div><div className="actions"><Link href={'/property/'+p.id}><button className="goldbtn detailsBtn">عرض التفاصيل</button></Link><Link href="/booking"><button className="outlinebtn">احجز معاينة</button></Link></div></div></article>}
function Properties({fav,setFav}:{fav:string[];setFav:(x:string[])=>void}){const [q,setQ]=useState('');const [type,setType]=useState('الكل');const [prov,setProv]=useState('كل المحافظات');const filtered=useMemo(()=>properties.filter(p=>(type==='الكل'||p.type===type)&&(prov==='كل المحافظات'||p.city===prov||p.city==='نينوى'&&prov==='الموصل')&&(`${p.title} ${p.area} ${p.city}`).includes(q)),[q,type,prov]);return <main className="container section"><div className="sectionhead"><div><div className="eyebrow">سوق العقارات العراقي</div><h1>اكتشف عقارك القادم</h1></div><Link href="/compare"><button className="outlinebtn">مقارنة العقارات</button></Link></div><div className="form"><div className="search" style={{margin:0,maxWidth:'none'}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن موقع أو اسم منطقة..."/><button className="goldbtn">بحث</button></div><div className="chips" style={{marginTop:12}}>{types.map(t=><button key={t} className={'chip '+(type===t?'active':'')} onClick={()=>setType(t)}>{t}</button>)}</div><select value={prov} onChange={e=>setProv(e.target.value)} style={{marginTop:12,padding:10,borderRadius:12}}>{provinces.map(x=><option key={x}>{x}</option>)}</select></div><div className="grid" style={{marginTop:18}}>{filtered.map(p=><Card key={p.id} p={p} fav={fav} setFav={setFav}/>)}{!filtered.length&&<div className="feature">لا توجد نتائج مطابقة. جرّب تغيير الفلاتر.</div>}</div></main>}
const sevenFeatures=[['✦','المساعد العقاري الذكي','/ai'],['⚖','مقارنة العقارات','/compare'],['📅','حجز موعد المعاينة','/booking'],['▣','الحاسبة العقارية و ROI','/calculator'],['📍','الموقع والاتجاهات','/properties'],['♥','العقارات المفضلة','/favorites'],['🛠','الحرفيون وخدمات البناء','/services']];
function Home({fav,setFav,dark,setDark}:{fav:string[];setFav:(x:string[])=>void;dark:boolean;setDark:(x:boolean)=>void}){return <main className="container"><section className="hero"><div className="eyebrow">منصة عقارية عراقية ذكية</div><h1>بيتك يبدأ من هنا.</h1><p>ابحث، قارن، احجز المعاينة، وتواصل مباشرة مع المالك. تجربة مصممة للسوق العراقي من كركوك إلى كل المحافظات.</p><div className="search"><input placeholder="ابحث عن موقع أو اسم منطقة..."/><Link href="/properties"><button className="goldbtn">استكشف العقارات</button></Link></div></section><section className="section"><div className="sectionhead"><h2>الوصول السريع</h2><button className="outlinebtn" onClick={()=>setDark(!dark)}>{dark?'☀ الوضع النهاري':'◐ الوضع الليلي'}</button></div><div className="proFeatureArea"><ProFeaturesButton /></div></section><section className="section"><div className="sectionhead"><h2>عقارات مميزة</h2><Link href="/properties">عرض الكل ←</Link></div><div className="grid">{properties.filter(p=>p.featured).slice(0,4).map(p=><Card key={p.id} p={p} fav={fav} setFav={setFav}/>)}</div></section></main>}
function Detail({id}:{id:string}){const p=properties.find(x=>x.id===id)||properties[0];return <main className="container section"><Link href="/properties">← العودة للعقارات</Link><div className="card" style={{marginTop:16}}><div className="photo" style={{height:360}}><img src={p.img} alt=""/></div><div className="body"><div className="eyebrow">{p.city} · {p.area}</div><h1>{p.title}</h1><div className="price">{money(p.price)}</div><p className="muted">المساحة {p.size} م² {p.rooms?` · ${p.rooms} غرف`:''} · الموقع متاح على الخريطة</p><div className="features"><div className="feature"><strong>📍 الموقع والاتجاه</strong><span className="muted">عرض الموقع التقريبي وفتح الاتجاهات.</span></div><div className="feature"><strong>📈 ROI</strong><span className="muted">تقدير العائد الاستثماري من الحاسبة.</span></div></div><div className="actions"><Link href="/booking"><button className="goldbtn">احجز موعد معاينة</button></Link><button className="outlinebtn" onClick={()=>window.open('https://wa.me/9647500000000','_blank')}>واتساب المالك</button></div></div></div></main>}
function Page({slug,fav,setFav,dark,setDark}:{slug:string[];fav:string[];setFav:(x:string[])=>void;dark:boolean;setDark:(x:boolean)=>void}){const path=slug.join('/');if(path==='')return <Home fav={fav} setFav={setFav} dark={dark} setDark={setDark}/>;if(path==='properties')return <Properties fav={fav} setFav={setFav}/>;if(path.startsWith('property/'))return <Detail id={path.split('/')[1]}/>;if(path==='favorites')return <main className="container section"><h1>المفضلة</h1><div className="grid">{properties.filter(p=>fav.includes(p.id)).map(p=><Card key={p.id} p={p} fav={fav} setFav={setFav}/>)}</div>{!fav.length&&<div className="feature">لم تضف عقارات للمفضلة بعد.</div>}</main>;if(path==='booking')return <main className="container section"><h1>حجز موعد المعاينة</h1><div className="form"><p className="muted">اختر اليوم والوقت المناسبين، وسيتم حفظ طلبك على هذا الجهاز.</p><div className="field"><label>العقار</label><select><option>دار سكنية حديثة في حي الواسطي</option><option>شقة راقية قرب شارع بغداد</option></select></div><div className="field"><label>التاريخ</label><input type="date"/></div><div className="field"><label>الوقت</label><select><option>04:00 مساءً</option><option>05:00 مساءً</option><option>06:00 مساءً</option></select></div><button className="goldbtn" onClick={()=>alert('تم تسجيل طلب المعاينة بنجاح')}>تأكيد الحجز</button></div></main>;if(path==='publish')return <main className="container section"><h1>نشر عقار</h1><div className="form"><div className="field"><label>عنوان العقار</label><input placeholder="مثال: دار حديثة في حي..."/></div><div className="field"><label>المحافظة</label><select>{provinces.slice(1).map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>النوع</label><select>{types.slice(1).map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>السعر التقريبي</label><input type="number" placeholder="د.ع"/></div><div className="field"><label>الوصف</label><textarea rows={5} placeholder="أضف التفاصيل والمميزات..."/></div><button className="goldbtn" onClick={()=>alert('تم إرسال العقار للمراجعة، ولن يظهر للعامة قبل موافقة الإدارة.')}>إرسال للمراجعة</button></div></main>;if(path==='compare')return <main className="container section"><h1>مقارنة العقارات</h1><div className="grid">{properties.slice(0,3).map(p=><div className="feature" key={p.id}><strong>{p.title}</strong><p>{money(p.price)}</p><p className="muted">{p.size} م² · {p.city}</p><p>السعر/م²: {money(Math.round(p.price/p.size))}</p></div>)}</div></main>;if(path==='calculator')return <Calculator/>;if(path==='ai')return <AI/>;if(path==='services')return <Services/>;if(path==='store')return <Store/>;if(path==='cart')return <Cart/>;if(path==='account')return <Account/>;return <main className="container section"><h1>الصفحة غير موجودة</h1><Link href="/">العودة للرئيسية</Link></main>}
function Calculator(){const [price,setPrice]=useState(150000000);const [rent,setRent]=useState(900000);const [years,setYears]=useState(10);const roi=price?((rent*12/price)*100).toFixed(2):'0';return <main className="container section"><h1>الحاسبة العقارية الذكية</h1><div className="form"><div className="field"><label>قيمة العقار</label><input type="number" value={price} onChange={e=>setPrice(+e.target.value)}/></div><div className="field"><label>الإيجار الشهري المتوقع</label><input type="number" value={rent} onChange={e=>setRent(+e.target.value)}/></div><div className="field"><label>مدة الاستثمار بالسنوات</label><input type="number" value={years} onChange={e=>setYears(+e.target.value)}/></div><div className="stats"><div className="stat"><span className="muted">ROI سنوي</span><br/><b>{roi}%</b></div><div className="stat"><span className="muted">دخل الإيجار خلال المدة</span><br/><b>{money(rent*12*years)}</b></div><div className="stat"><span className="muted">نقطة التعادل</span><br/><b>{rent?((price/(rent*12)).toFixed(1))+' سنة':'—'}</b></div></div></div></main>}
function AI(){const [q,setQ]=useState('');const [result,setResult]=useState('');return <main className="container section"><h1>المساعد العقاري الذكي</h1><div className="form"><p className="muted">اكتب طلبك باللهجة العراقية أو بالعربية، مثل: أريد دار بكركوك أقل من 200 مليون.</p><textarea rows={4} value={q} onChange={e=>setQ(e.target.value)} placeholder="اكتب طلبك هنا..."/><button className="goldbtn" onClick={()=>{const m=q.match(/(\d+)\s*(مليون|مليار)/);const max=m?(m[2]==='مليار'?+m[1]*1000000000:+m[1]*1000000):Infinity;const hits=properties.filter(p=>(q.includes(p.type)||q.includes('عقار')||q.includes('دار')&&p.type==='دار'||q.includes('شقة')&&p.type==='شقة')&&p.price<=max);setResult(hits.length?`وجدت ${hits.length} عقار مناسب.`:'لم أجد تطابقاً واضحاً، جرّب كلمات أخرى.') } }>حلّل الطلب</button>{result&&<div className="feature" style={{marginTop:12}}>{result}<div style={{marginTop:10}}><Link href="/properties">فتح كل العقارات ←</Link></div></div>}</div></main>}
function Services(){return <main className="container section"><h1>الحرفيون وخدمات البناء</h1><div className="grid">{['كهربائي','سباك','صباغ','حداد','تكييف وتبريد','بناء وترميم'].map(x=><div className="feature" key={x}><strong>{x}</strong><p className="muted">خدمة محلية موثوقة.</p><button className="goldbtn" onClick={()=>alert(`سيتم عرض مقدمي خدمة ${x} قريباً`)}>عرض مقدمي الخدمة</button></div>)}</div></main>}
function Store(){const items=['مواد بناء','أدوات كهربائية','أدوات سباكة','دهانات','أدوات حدادة','مستلزمات منزلية'];return <main className="container section"><h1>متجر عقاري</h1><div className="grid">{items.map(x=><div className="feature" key={x}><strong>{x}</strong><p className="muted">منتجات مختارة للمشاريع العقارية.</p><button className="goldbtn" onClick={()=>alert('تمت إضافة المنتج للسلة')}>أضف للسلة</button></div>)}</div></main>}
function Cart(){return <main className="container section"><h1>سلة المشتريات</h1><div className="feature">السلة جاهزة لاستقبال المنتجات التي تختارها من المتجر.</div></main>}
function Account(){return <main className="container section"><h1>حسابي</h1><div className="form"><p className="muted">يمكنك التصفح بدون حساب. سجّل حساباً للوصول إلى بيانات المالك والخدمات الخاصة.</p><button className="goldbtn" onClick={()=>alert('سيتم فتح التسجيل قريباً')}>تسجيل / دخول</button></div></main>}
export default function PageClient({slug}:{slug:string[]}){const [fav,setFav]=useState<string[]>([]);const [dark,setDark]=useState(false);useEffect(()=>{try{setFav(JSON.parse(localStorage.getItem('aqari-favorites')||'[]'))}catch{}},[]);useEffect(()=>{localStorage.setItem('aqari-favorites',JSON.stringify(fav))},[fav]);return <div className={dark?'dark':''}><Nav/><Page slug={slug} fav={fav} setFav={setFav} dark={dark} setDark={setDark}/></div>}
