const FEATURES=[['purchase','🏠','محاكي شراء العقار'],['build','🧱','حاسبة بناء العقار'],['handover','🔑','تسليم العقار'],['dark','🌙','الوضع الليلي'],['exchange','🤝','مبادلة العقارات'],['investment','📈','الاستثمار العقاري'],['daily','⭐','عقار اليوم']];
const money=n=>new Intl.NumberFormat('en-US').format(Math.round(Number(n)||0))+' د.ع';
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const getProps=()=>{const live=Array.isArray(window.__AQARI_PROPS__)?window.__AQARI_PROPS__:[];try{const saved=JSON.parse(localStorage.getItem('aqariProperties')||'[]');return [...live,...saved.filter(x=>!live.some(y=>String(y.id)===String(x.id)))];}catch{return live;}};
const css=`#aqari-feature-router{direction:rtl;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif}#aqari-feature-router *{box-sizing:border-box}.aqRPanel{max-width:540px;margin:14px auto;padding:16px;border-radius:24px;background:linear-gradient(145deg,#071d35,#0b3453);color:#fff;border:1px solid #d9a441}.aqRGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:14px}.aqRBtn{appearance:none;width:100%;min-height:98px;border:1px solid #31516b;border-radius:17px;background:#102f4d;color:#fff;text-align:right;padding:12px;cursor:pointer;touch-action:manipulation}.aqRBtn i{display:block;font-style:normal;font-size:25px}.aqRBtn strong,.aqRBtn small{display:block}.aqRBtn strong{font-size:12px;margin-top:6px}.aqRBtn small{font-size:9px;opacity:.7;margin-top:4px}.aqRScreen{position:fixed;inset:0;z-index:2147483647;overflow:auto;background:#f7f9fb;color:#101828;padding:18px 14px 70px}.aqRScreen>*{max-width:560px;margin-left:auto;margin-right:auto}.aqBack{appearance:none;border:0;background:#071d35;color:#fff;border-radius:14px;padding:11px 17px;font-size:14px;cursor:pointer}.aqRScreen h1{font-size:23px;color:#071d35;margin:20px auto 8px}.aqRScreen p{color:#667085;line-height:1.7}.aqField{display:block;margin:14px auto}.aqField span{display:block;font-size:12px;font-weight:800;margin-bottom:6px}.aqField input,.aqField select,.aqField textarea{width:100%;padding:13px;border:1px solid #d0d5dd;border-radius:14px;background:#fff;color:#101828;font:inherit}.aqField textarea{min-height:110px}.aqAction{appearance:none;width:100%;padding:14px;border:0;border-radius:15px;background:#071d35;color:#fff;font-weight:800;margin:4px 0 14px;cursor:pointer}.aqRes{display:flex;justify-content:space-between;gap:12px;background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:13px;margin:8px 0}.aqRes b,.aqRes small{display:block}.aqRes small{font-size:10px;color:#667085;margin-top:4px}.aqRes strong{color:#071d35;white-space:nowrap}.aqKpi{display:grid;grid-template-columns:1fr 1fr;gap:9px}.aqKpi b{background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:16px;text-align:center;color:#071d35}.aqKpi small{display:block;font-size:10px;color:#667085}.aqCheck{background:#fff;border-radius:18px;border:1px solid #e4e7ec;padding:8px 14px}.aqCheck label{display:block;padding:13px 0;border-bottom:1px solid #eee}.aqChosen{background:#071d35;color:#fff;border-radius:17px;padding:15px}.aqChosen span{display:block;margin-top:6px;color:#d9a441}.aqDaily{background:#071d35;color:#fff;border-radius:22px;padding:14px}.aqDaily img{width:100%;height:230px;object-fit:cover;border-radius:16px}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function renderResults(rows){return rows.length?rows.map(x=>`<article class="aqRes"><div><b>${esc(x.t)}</b><small>📍 ${esc(x.city)} - ${esc(x.d)} • ${x.a} م²</small></div><strong>${money(x.p)}</strong></article>`).join(''):'<p>ماكو عقارات مطابقة حالياً ضمن البيانات المتاحة.</p>';}
function closeScreen(){document.querySelector('#aqari-feature-router .aqRScreen')?.remove();}
function featureScreen(id){closeScreen();const props=getProps(),root=document.getElementById('aqari-feature-router'),f=FEATURES.find(x=>x[0]===id);if(!root||!f)return;let html=`<main class="aqRScreen"><button class="aqBack" type="button">→ رجوع</button><h1>${f[1]} ${f[2]}</h1>`;
if(id==='purchase'||id==='build'){const types=[...new Set(props.map(x=>x.c).filter(Boolean))];html+=`<p>${id==='purchase'?'حدد نوع العقار والميزانية لعرض العقارات الموجودة فعلياً.':'تقدير أولي مبني على أسعار العقارات الحالية داخل عقاري.'}</p><label class="aqField"><span>نوع العقار</span><select id="aqType">${types.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label class="aqField"><span>الميزانية القصوى</span><input id="aqBudget" type="number" inputmode="numeric" placeholder="200000000"></label><button class="aqAction" id="aqRun">${id==='purchase'?'عرض العقارات المطابقة':'احسب الآن'}</button><div id="aqOut"></div>`;
}else if(id==='handover'){html+=`<p>عملية تسليم مرتبة وواضحة من الفحص إلى توقيع محضر التسليم.</p><label class="aqField"><span>العقار</span><select id="aqProp">${props.map(x=>`<option value="${esc(x.id)}">${esc(x.t)} — ${money(x.p)}</option>`).join('')}</select></label><div class="aqCheck">${['مطابقة الهوية','مراجعة الملكية','فحص العقار','الكهرباء والماء','تسليم المفاتيح','توقيع محضر التسليم'].map((x,i)=>`<label><input type="checkbox" data-check="${i}"> ${x}</label>`).join('')}</div><button class="aqAction" id="aqSave">حفظ سجل التسليم</button>`;
}else if(id==='exchange'){html+=`<p>اختر عقارك وأدخل شروط المبادلة، ثم ستظهر أقرب الفرص من العقارات الحالية.</p><label class="aqField"><span>عقاري</span><select id="aqMine">${props.map(x=>`<option value="${esc(x.id)}">${esc(x.t)} — ${money(x.p)}</option>`).join('')}</select></label><div id="aqChosen"></div><label class="aqField"><span>شروط المبادلة</span><textarea id="aqWant" placeholder="مثلاً: أريد بيتاً في حي هادئ مع فرق سعر مناسب"></textarea></label><button class="aqAction" id="aqExchange">عرض فرص المبادلة</button><div id="aqOut"></div>`;
}else if(id==='investment'){const rows=props.map(x=>({...x,yieldPct:x.p&&x.r?x.r*12/x.p*100:0})).sort((a,b)=>b.yieldPct-a.yieldPct);html+=`<p>مؤشرات استثمارية تقديرية اعتماداً على سعر الشراء والإيجار المسجل للعقار.</p>${rows.map(x=>`<article class="aqRes"><div><b>${esc(x.t)}</b><small>📍 ${esc(x.city)} - ${esc(x.d)} • ${x.a} م²</small><small>📈 عائد سنوي تقريبي ${x.yieldPct.toFixed(1)}%</small></div><strong>${money(x.p)}</strong></article>`).join('')}`;
}else if(id==='daily'){const p=props[0];html+=p?`<div class="aqDaily"><img src="${esc(p.img)}" alt=""><b>⭐ فرصة اليوم</b><h2>${esc(p.t)}</h2><p>${esc(p.city)} - ${esc(p.d)}</p><strong>${money(p.p)}</strong><div class="aqRes"><div><b>تفاصيل العقار</b><small>📐 ${p.a} م² • 🛏️ ${p.r||0} غرف • ♨️ ${p.b||0} حمامات</small></div><strong>${money(p.p)}</strong></div></div>`:'<p>لا توجد عقارات حالياً.</p>';
}
root.insertAdjacentHTML('beforeend',html+'</main>');const s=root.querySelector('.aqRScreen');s.querySelector('.aqBack').onclick=closeScreen;
if(id==='purchase'||id==='build')s.querySelector('#aqRun').onclick=()=>{const type=s.querySelector('#aqType').value,b=Number(s.querySelector('#aqBudget').value)||0;if(id==='purchase')s.querySelector('#aqOut').innerHTML=renderResults(props.filter(x=>x.c===type&&(!b||x.p<=b)));else{const a=props.filter(x=>x.c===type),avg=a.length?a.reduce((v,x)=>v+x.p/x.a,0)/a.length:0;s.querySelector('#aqOut').innerHTML=`<div class="aqKpi"><b>${b&&avg?Math.floor(b/avg):'—'}<small>م² تقريباً</small></b><b>${money(avg)}<small>سعر المتر التقديري</small></b></div>${renderResults(a)}`;}};
if(id==='handover')s.querySelector('#aqSave').onclick=()=>{localStorage.setItem('aqariHandover',JSON.stringify({propertyId:s.querySelector('#aqProp').value,done:[...s.querySelectorAll('[data-check]')].filter(x=>x.checked).map(x=>x.dataset.check),updatedAt:new Date().toISOString()}));s.querySelector('#aqSave').textContent='✓ تم حفظ سجل التسليم';};
if(id==='exchange'){const update=()=>{const p=props.find(x=>String(x.id)===s.querySelector('#aqMine').value);s.querySelector('#aqChosen').innerHTML=p?`<div class="aqChosen"><b>${esc(p.t)}</b><span>${p.a} م² • ${money(p.p)}</span></div>`:'';};s.querySelector('#aqMine').onchange=update;update();s.querySelector('#aqExchange').onclick=()=>{const mine=props.find(x=>String(x.id)===s.querySelector('#aqMine').value),rows=props.filter(x=>x.id!==mine?.id).sort((a,b)=>Math.abs(a.p-(mine?.p||0))-Math.abs(b.p-(mine?.p||0))).slice(0,5);localStorage.setItem('aqariExchangeRequest',JSON.stringify({propertyId:mine?.id,want:s.querySelector('#aqWant').value,updatedAt:new Date().toISOString()}));s.querySelector('#aqOut').innerHTML=renderResults(rows);};}}
function toggleNight(){const on=!document.body.classList.contains('aqNight');document.body.classList.toggle('aqNight',on);localStorage.setItem('aqNight',on?'1':'0');}
function mount(){if(document.getElementById('aqari-feature-router'))return;const root=document.createElement('div');root.id='aqari-feature-router';root.innerHTML=`<section class="aqRPanel"><div><b>✨ مميزات عقاري الذكية</b><small style="display:block;opacity:.75;margin-top:5px">اضغط على أي ميزة وستفتح مباشرة بدون نافذة منبثقة</small></div><div class="aqRGrid">${FEATURES.map(f=>`<button type="button" class="aqRBtn" data-feature="${f[0]}"><i>${f[1]}</i><strong>${f[2]}</strong><small>فتح الآن ←</small></button>`).join('')}</div></section>`;document.body.appendChild(root);root.addEventListener('click',e=>{const b=e.target.closest('[data-feature]');if(!b)return;const id=b.dataset.feature;if(id==='dark')toggleNight();else featureScreen(id);});}
/* إلغاء أي نظام Modal قديم ما زال محملاً، واعتراض أزراره قبل وصول الحدث إلى الكود القديم. */
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-aq]');if(!b)return;const map={purchase:'purchase',build:'build',handover:'handover',exchange:'exchange',investment:'investment',daily:'daily',dark:'dark'};const id=map[b.getAttribute('data-aq')];if(!id)return;e.preventDefault();e.stopImmediatePropagation();if(id==='dark')toggleNight();else featureScreen(id);},true);
new MutationObserver(()=>document.querySelectorAll('.aq-modal,.aq-box').forEach(x=>{if(!x.closest('#aqari-feature-router'))x.remove();})).observe(document.body,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();