import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const cats=['منازل','شقق','قطع أراضي','مشتملات','محلات','مخازن'];
const props=[
{id:1,t:'بيت سكني حديث',c:'منازل',city:'كركوك',d:'رحيم آغا',p:385000000,a:250,r:4,b:3,s:2,park:1,phone:'07700000001',img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',imgs:['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85']},
{id:2,t:'شقة عصرية راقية',c:'شقق',city:'كركوك',d:'تسعين',p:175000000,a:145,r:3,b:2,s:1,park:1,phone:'07700000002',img:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85',imgs:['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85']},
{id:3,t:'قطعة أرض سكنية',c:'قطع أراضي',city:'كركوك',d:'الواسطي',p:120000000,a:300,r:0,b:0,s:0,park:0,phone:'07700000003',img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85',imgs:['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85']},
{id:4,t:'مشتمل مستقل',c:'مشتملات',city:'كركوك',d:'غرناطة',p:95000000,a:120,r:2,b:2,s:1,park:1,phone:'07700000004',img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85',imgs:['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85']},
{id:5,t:'منزل عائلي واسع',c:'منازل',city:'كركوك',d:'شورجة',p:290000000,a:220,r:4,b:3,s:2,park:2,phone:'07700000005',img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85',imgs:['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85']},
{id:6,t:'فيلا حديثة',c:'منازل',city:'كركوك',d:'الماس',p:550000000,a:400,r:5,b:4,s:3,park:2,phone:'07700000006',img:'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=85',imgs:['https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=85']}
];
const money=n=>new Intl.NumberFormat('en-US').format(n)+' د.ع';
function App(){const[page,setPage]=useState('home'),[q,setQ]=useState(''),[cat,setCat]=useState('الكل'),[sel,setSel]=useState(null),[fav,setFav]=useState([]),[role,setRole]=useState(null),[slide,setSlide]=useState(0);const list=useMemo(()=>props.filter(x=>(cat==='الكل'||x.c===cat)&&(`${x.t}${x.city}${x.d}`).includes(q)),[q,cat]);const open=x=>{setSel(x);setSlide(0);setPage('detail')};const toggle=id=>setFav(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);return <div className="app">
{page==='home'&&<><header><div><b>عقاري</b><small>سوق كركوك</small></div><span className="logo">ع</span></header><div className="search" onClick={()=>setPage('search')}>⌕ <span>ابحث عن موقع أو اسم منطقة...</span></div><div className="quick"><button onClick={()=>setPage('search')}>⚙ الفلتر</button><button onClick={()=>setPage('search')}>💰 الحد الأقصى للسعر</button><button onClick={()=>setPage('search')}>📍 الموقع</button><button onClick={()=>{setCat('الكل');setQ('');setPage('search')}}>عرض الكل</button></div><div className="hero"><div><h1>عقارك القادم يبدأ من هنا</h1><p>اكتشف المنازل والشقق والأراضي في كركوك.</p><button onClick={()=>setPage('search')}>استكشف العقارات</button></div><strong>⌂</strong></div><Section title="التصنيفات"/><div className="cats"><button onClick={()=>{setCat('الكل');setPage('search')}}>⌂<span>الكل</span></button>{cats.map((x,i)=><button onClick={()=>{setCat(x);setPage('search')}} key={x}>{['⌂','▥','▱','▤','▣','▦'][i]}<span>{x}</span></button>)}</div><Section title="عقارات مميزة"/><div>{props.map(x=><Card key={x.id} p={x} open={()=>open(x)} fav={fav.includes(x.id)} toggle={()=>toggle(x.id)}/>)}</div></>}
{page==='search'&&<><Top title="البحث والفلاتر" back={()=>setPage('home')}/><div className="search full">⌕<input autoFocus placeholder="ابحث عن موقع أو اسم منطقة..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="chips"><button onClick={()=>setCat('الكل')} className={cat==='الكل'?'on':''}>الكل</button>{cats.map(x=><button key={x} onClick={()=>setCat(x)} className={cat===x?'on':''}>{x}</button>)}</div><p className="muted">{list.length} عقارات متاحة</p>{list.map(x=><Card key={x.id} p={x} open={()=>open(x)} fav={fav.includes(x.id)} toggle={()=>toggle(x.id)}/>)}</>}
{page==='detail'&&sel&&<><Top title="تفاصيل العقار" back={()=>setPage('home')}/><div className="gallery"><img src={sel.imgs[slide]}/>{sel.imgs.length>1&&<><button onClick={()=>setSlide((slide-1+sel.imgs.length)%sel.imgs.length)} className="arr l">‹</button><button onClick={()=>setSlide((slide+1)%sel.imgs.length)} className="arr r">›</button><div className="dots">{sel.imgs.map((_,i)=><i className={i===slide?'active':''} key={i}/>)}</div></>}</div><div className="detail"><div className="row"><span className="tag">{sel.c}</span><button className="heart" onClick={()=>toggle(sel.id)}>{fav.includes(sel.id)?'♥':'♡'}</button></div><p className="muted">📍 {sel.city} · {sel.d}</p><h1>{sel.t}</h1><h2>{money(sel.p)}</h2><div className="spec"><b>{sel.a} م²<small>المساحة</small></b><b>{sel.r||'—'}<small>غرف النوم</small></b><b>{sel.b||'—'}<small>الحمامات</small></b><b>{sel.park||'—'}<small>المواقف</small></b></div><h3>وصف العقار</h3><p>عقار مميز بموقع جيد داخل كركوك، مناسب للسكن والاستثمار. جميع البيانات المعروضة تجريبية ويمكن استبدالها ببيانات الإعلانات الحقيقية.</p><div className="map">📍<b>موقع العقار على الخريطة</b><small>موقع افتراضي — يمكن ربط الخريطة لاحقاً</small></div><div className="actions"><button onClick={()=>location.href='tel:'+sel.phone}>📞 اتصال</button><button onClick={()=>window.open('https://wa.me/964'+sel.phone.replace(/^0/,''),'_blank')} className="green">💬 WhatsApp</button></div></div></>}
{page==='auth'&&<div className="auth"><span className="logo big">ع</span><h1>أهلاً بك في عقاري</h1><p>اختر نوع الحساب</p><button onClick={()=>{setRole('customer');setPage('home')}}>👤 زبون<small>تصفح، مفضلة وتواصل</small></button><button onClick={()=>{setRole('owner');setPage('home')}}>⌂ صاحب عقار<small>انشر وأدر عقاراتك</small></button><a onClick={()=>setPage('home')}>يمكنك التصفح بدون حساب</a></div>}
{page==='favorites'&&<><Top title="المفضلة" back={()=>setPage('home')}/>{props.filter(x=>fav.includes(x.id)).map(x=><Card key={x.id} p={x} open={()=>open(x)} fav toggle={()=>toggle(x.id)}/>)}{!fav.length&&<div className="empty">♡<b>لا توجد مفضلة بعد</b><span>اضغط القلب على أي عقار لحفظه هنا.</span></div>}</>}
{page==='messages'&&<><Top title="الرسائل" back={()=>setPage('home')}/><div className="empty">💬<b>لا توجد رسائل</b><span>ستظهر محادثاتك مع أصحاب العقارات هنا.</span></div></>}
<nav><button className={page==='home'?'active':''} onClick={()=>setPage('home')}>⌂<small>الرئيسية</small></button><button className={page==='search'?'active':''} onClick={()=>setPage('search')}>⌕<small>بحث</small></button><button className="plus" onClick={()=>role==='owner'?alert('نموذج إضافة الإعلان جاهز للربط بقاعدة البيانات'):setPage('auth')}>＋</button><button className={page==='favorites'?'active':''} onClick={()=>setPage('favorites')}>♡<small>المفضلة</small></button><button className={page==='messages'?'active':''} onClick={()=>setPage('messages')}>💬<small>الرسائل</small></button></nav></div>}
const Section=({title})=><div className="section"><h2>{title}</h2><a onClick={()=>{}}>عرض الكل</a></div>;const Top=({title,back})=><div className="top"><button onClick={back}>→</button><h2>{title}</h2><span/></div>;function Card({p,open,fav,toggle}){return <article onClick={open}><div className="cardImg"><img src={p.img}/><button className="heart" onClick={e=>{e.stopPropagation();toggle()}}>{fav?'♥':'♡'}</button><span className="tag">{p.c}</span></div><div className="cardBody"><div className="cardTop"><div><small>📍 {p.city} - {p.d}</small><h3>{p.t}</h3></div><b>{money(p.p)}</b></div><div className="mini"><span>▣ {p.a} م²</span><span>🛏 {p.r}</span><span>♨ {p.b}</span><span>🚗 {p.park}</span></div><button className="details">تفاصيل أكثر</button></div></article>}createRoot(document.getElementById('root')).render(<App/>);